--- 
abstract: Automatically tokenize a column on creation
author: 
  - J. Shirley, C<< <jshirley at coldhardcode.com> >>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-Tokenize
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBIx::Class: 0
version: 0.01
